# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Remove symlinks (Fix GitHub Pages deployment)
        run: find _site -type l -delete

      - name: Debug- List contents of _site
        run: ls -lR _site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        path: ./_site
        with:
          name: github-pages
          path: ./_site
          retention-days: 1 # Ensure the artifact is retained for at least 1 day

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site

      - name: Debug-Check downloaded artifact contents
        run: ls -lR ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
